### PR TITLE
deps need lodash 3 peer

### PR DESCRIPTION
**Pull request by boygirl**

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@boygirl -- Can you walk me through the error you're encountering and what packages expect which lodash that they're _not_ getting?

**Comment by boygirl** [comment]
I can't tell what isn't getting fulfilled, but my build ends up with this error: 

```
ERROR in Cannot find module 'lodash/lang/isFunction'
```

**Comment by ryan-roemer** [comment]
@boygirl -- Can you point me to the Travis build in question?

**Comment by boygirl** [comment]
In a moment I will fix the _other_ things breaking my build in travis, and then I can ;)

**Pull request closed without merging**
