### PR TITLE
Webpack3 + ES6 Exports

### LINKED ISSUE #256: Provide es6 build to use with Webpack 2
I'm using Webpack 2 on https://status.postmarkapp.com and would like to reduce the bundle size of the production bundle. ATM there is no easy way to use webpack's tree-shaking since vicotry code get's transpiled to es5 and commonjs.

In the meantime, is there a way to minimize bundle size with CommonJS?

### LINKED ISSUE #548: Provide efficient webpack helpers for tree-shaking + DCE
Moving discussion from https://github.com/FormidableLabs/victory/issues/547 to the broader one: how to provide end users with the most terse bundle. I forget how much we talked about this before, but we could do a `package.json:browser` or `package.json:SOME_OTHER_MAIN` that webpack picks up that points to `src`, but then run into the problem of **everyone** needing fully compatible babel builds.

## 1. Alias Option

One option is providing the resolves `src` paths as in the experiment repo's `webpack` config as a top-level provided thing so in your webpack config you could do something like:

```js
const victorySrcAliases = require("victory/webpack").victorySrcAliases;
// {
//   "victory-core": "RESOLVE/PATH/victory-core/src",
//   "victory-chart": "RESOLVE/PATH/victory-chart/src",
//   // ...
// }

module.exports = {
  // ...
  module: {
    loaders: [
      {
        test: /\.js$/,
        include: [
          path.resolve("src"),
        ].concat(
          Object.keys(victorySrcAliases).map((k) => victorySrcAliases[k])
        )
        loader: "babel-loader"
      }
    ]
  },
  resolve: {
    alias: {
      // Force use of es6 src instead of es5 lib
      ...victorySrcAliases
    }
  },
  // ...
};
```

## 2. Different Main Option

A perhaps lighterweight custom idea is provide a custom `victory` specific namespace for: https://webpack.github.io/docs/configuration.html#resolve-packagemains that _isn't_ in the defaults for webpack1: `["webpack", "browser", "web", "browserify", ["jam", "main"], "main"]`

The reason why we need to avoid the defaults is otherwise **everyone** would need the victory-specific babel set up to be able to use victory, which isn't what we want.

So, like `package.json:browser-victory` that folks then explicitly _add_ to webpack1 `resolve.packageMains` to then need + use babel building like in the experiment repo at: https://github.com/FormidableLabs/victory-line-experiments

```js
// node_modules/victory*/package.json
"victory-browser": "src/index.js",
"main": "lib/index.js",

// my-project/webpack.config.js
resolve: {
  packageMains: ["victory-browser", "main"]
}
```

Also, we need a webpack2-amenable configuration that also works with the decided scheme: https://webpack.js.org/configuration/resolve/#resolve-mainfields

Current strawman:

```
"browser": "lib/index.js",
"main": "lib/index.js",
"module": "es/index.js",
"victory-module": "es/index.js"
```

- [ ] Requires transpiling to `es` directory (out of source, but published) like `redux` does.
- [ ] Consider a transform to convert es index imports to one-off-full-file-path imports -- https://bitbucket.org/amctheatres/babel-transform-imports -- to help mitigate #549 

For a good reference, see: https://github.com/reactjs/redux/blob/master/package.json

```js
  "browser": "dist/redux.js",
  "main": "lib/index.js",
  "module": "es/index.js",
  "jsnext:main": "es/index.js",

  // ...
  "scripts": {
    "build:commonjs": "cross-env BABEL_ENV=commonjs babel src --out-dir lib",
    "build:es": "cross-env BABEL_ENV=es babel src --out-dir es",
    "build:umd": "cross-env BABEL_ENV=es NODE_ENV=development rollup -c -i src/index.js -o dist/redux.js",
    "build:umd:min": "cross-env BABEL_ENV=es NODE_ENV=production rollup -c -i src/index.js -o dist/redux.min.js",
```

## Other Notes:

- [ ] Audit and confirm Victory unused stuff is dropped. We've seen stuff like the following from uglify that may indicate not dropped correctly? (Or maybe this warn is safe to ignore)

```
Side effects in initialization of unused variable __WEBPACK_IMPORTED_MODULE_0__victory_animation_victory_animation__ [main.js:94,25]
````

/cc @boygirl @chrisbolin @thomasthiebaud

### PR DESCRIPTION
**Pull request by ryan-roemer**
This PR modernizes the Victory build and offerings. Generally:

- Provide an `es/` directory alongside `lib/` that has ES module export / imports (but everything else babel built) per the `redux` model. This model allows webpack2+ to use ESM resolution and enable tree-shaking, while is still backwards compatible with webpack1 which will use `lib/`
- Remove all references to `.jsx` since we don't use those anymore.
- Clean up and hone down a lot of stuff.

/cc @boygirl @chrisbolin

### Cross-reference PRs

First, infrastructure:

* https://github.com/FormidableLabs/builder-victory-component-dev/pull/7
* https://github.com/FormidableLabs/builder-victory-component/pull/92

Second, core:

* https://github.com/FormidableLabs/victory-core/pull/266

Third, dependers:

* https://github.com/FormidableLabs/victory-pie/pull/149
* https://github.com/FormidableLabs/victory-chart/pull/495

Finally, parent:

* https://github.com/FormidableLabs/victory/pull/651

### Tickets

Implemented / fixed:

- Provide es6 build to use with Webpack. Fixes https://github.com/FormidableLabs/victory/issues/256
- Provide efficient webpack helpers for tree-shaking + DCE. Fixes https://github.com/FormidableLabs/victory/issues/548

Opened / still open:

- Webpack tree shaking does not completely remove unused re-exports. https://github.com/FormidableLabs/victory/issues/549

### Bundles

The main goal here is not the victory _bundle_, but enabling webpack2+ users to get more efficient builds going off the `es/` directory. And with the dedupe plugin being removed in webpack2+, our dev bundle is definitely bigger. But, fortunately, the prod minified bundles aren't that different:

*Before / webpack1*

```
$ find ../victory*/dist -type f -exec wc -c {} \;
  993198 ../victory-chart/dist/victory-chart.js
 1323555 ../victory-chart/dist/victory-chart.js.map
  438868 ../victory-chart/dist/victory-chart.min.js
 2634923 ../victory-chart/dist/victory-chart.min.js.map
  659513 ../victory-core/dist/victory-core.js
  915723 ../victory-core/dist/victory-core.js.map
  276427 ../victory-core/dist/victory-core.min.js
 1734458 ../victory-core/dist/victory-core.min.js.map
  674687 ../victory-pie/dist/victory-pie.js
  836742 ../victory-pie/dist/victory-pie.js.map
  284790 ../victory-pie/dist/victory-pie.min.js
 1814890 ../victory-pie/dist/victory-pie.min.js.map
 1013340 ../victory/dist/victory.js
 1235399 ../victory/dist/victory.js.map
  450323 ../victory/dist/victory.min.js
 2747731 ../victory/dist/victory.min.js.map
```

*After / webpack3*

```
$ find ../victory*/dist -type f -exec wc -c {} \;
 1663000 ../victory-chart/dist/victory-chart.js
 1602704 ../victory-chart/dist/victory-chart.js.map
  434851 ../victory-chart/dist/victory-chart.min.js
 3349108 ../victory-chart/dist/victory-chart.min.js.map
  975040 ../victory-core/dist/victory-core.js
  941706 ../victory-core/dist/victory-core.js.map
  265075 ../victory-core/dist/victory-core.min.js
 1930341 ../victory-core/dist/victory-core.min.js.map
 1219152 ../victory-pie/dist/victory-pie.js
 1092945 ../victory-pie/dist/victory-pie.js.map
  304427 ../victory-pie/dist/victory-pie.min.js
 2396990 ../victory-pie/dist/victory-pie.min.js.map
 1869374 ../victory/dist/victory.js
 1680468 ../victory/dist/victory.js.map
  487115 ../victory/dist/victory.min.js
 3846520 ../victory/dist/victory.min.js.map
```

### CODE REVIEW

**Comment by boygirl** [comment]
@ryan-roemer I think this is failing linting

**Comment by ryan-roemer** [comment]
@boygirl -- Yep. Fixed.

**Comment by boygirl** [comment]
@ryan-roemer once this goes in, I'd like to do a major version bump on the archetypes. Does that sounds appropriate?

**Comment by ryan-roemer** [comment]
@boygirl -- Yep. Major for archetypes. But fortunately, minor for victory repos.

**Pull request merged**
